[server]
headless = true

# .streamlit/config.toml

# Sets the default theme. "light" or "dark".
[theme]
primaryColor="#4fa47d"
backgroundColor="#f1e8eb"
secondaryBackgroundColor="#e4d3e0"
textColor="#0e1117"

