[server]
headless = true

# .streamlit/config.toml

# Sets the default theme. "light" or "dark".
[theme]
primaryColor="#4fa47d"
backgroundColor="#ffc0cb"
secondaryBackgroundColor="#e1e2ef"
textColor="#0e1117"
